os: osx
osx_image: xcode10.1
language: swift
xcode_workspace: FoundSounds.xcworkspace # path to your xcodeproj folder
xcode_scheme: FoundSounds
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
